export const travelPlusEvents = [
  { slug: "team-building", title: "Team-building Retreat", image: "team-building.jpg", alt: "A team working together in an outdoor tug-of-war", description: "Bring your team together at a beach resort or mountain retreat. Outdoor activities, workshops, and shared challenges build communication and collaboration." },
  { slug: "industry-conference", title: "Industry Conference", image: "conference.jpg", alt: "An audience taking part in a conference", description: "Connect professionals, experts, and industry leaders through conferences and trade shows designed for networking, knowledge sharing, and new ideas." },
  { slug: "incentive-travel", title: "Incentive Travel Program", image: "incentive.jpg", alt: "A group exploring a scenic walking trail together", description: "Reward your people with exclusive experiences, luxury stays, and curated activities. A thoughtful way to recognise employees, clients, and top performers." },
  { slug: "product-launch", title: "Product Launch Event", image: "launch.jpg", alt: "Confetti falling over a lively event crowd", description: "Introduce your next product or service with an event for stakeholders, media, and customers, brought to life through presentations, demonstrations, and interactive experiences." },
  { slug: "annual-general-meeting", title: "Annual General Meeting (AGM)", image: "agm.jpg", alt: "Meeting attendees with notebooks ready for discussion", description: "Bring shareholders, board members, and stakeholders together to review performance and discuss future goals, with presentations, reports, and time for questions." },
  { slug: "gala-dinner", title: "Corporate Gala Dinner", image: "gala.jpg", alt: "Guests raising their glasses at a celebratory dinner", description: "Mark achievements and milestones with fine dining, live entertainment, and awards in an elegant setting that celebrates your people and their contributions." },
  { slug: "leadership-summit", title: "Leadership Summit", image: "leadership.jpg", alt: "A group joining hands in a gesture of teamwork", description: "Create space for executives and business leaders to explore strategy and industry trends through keynote talks, panel discussions, and collaborative workshops." },
  { slug: "training-workshop", title: "Training Workshop", image: "training.jpg", alt: "Participants attending a presentation in a training venue", description: "Help employees and clients develop their skills through expert-led seminars, hands-on sessions, and practical exercises shaped around their learning goals." },
  { slug: "charity-fundraising", title: "Charity Fundraising Event", image: "charity.jpg", alt: "Colourful bags prepared for a charitable initiative", description: "Unite donors, sponsors, and volunteers around a worthy cause. From gala dinners and auctions to charity runs, create an occasion that raises funds and awareness." },
  { slug: "destination-wedding", title: "Destination Wedding", image: "wedding.jpg", alt: "A wedding aisle decorated with flowers and gold chairs", description: "Celebrate your story in a beautiful destination. Bespoke wedding arrangements, personal service, and carefully chosen venues create a memorable experience for you and your guests." },
];
